config/routes.rb
Rails.application.routes.draw do
  resources :finances

  resources :teams

  resources :schools

  resources :years

  devise_for :users
  root "pages#login"
  get "traineeFinance" => "pages#traineeFinance"
  get "finance" => "finances#index"










end

app/models/finance.rb
class Finance < ActiveRecord::Base
	belongs_to :user
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :users
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
		 
	belongs_to :year
	has_many :finances
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  respond_to :html

  def index
    @finances = Finance.all
    respond_with(@finances)
  end

  def show
    respond_with(@finance)
  end

  def new
    @finance = current_user.finances.build
    respond_with(@finance)
  end

  def edit
  end

  def create
    @finance = current_user.finances.build(finance_params)
    @finance.save
    respond_with(@finance)
  end

  def update
    @finance.update(finance_params)
    respond_with(@finance)
  end

  def destroy
    @finance.destroy
    respond_with(@finance)
  end

  private
    def set_finance
      @finance = Finance.find_by(params[:id])
    end
	
	def correct_user
	  @finance = current_user.finances.find_by(id: params[:id])
	  redirect_to finances_path, notice: "Not authorized to edit this" if @finance.nil?
    end

    def finance_params
      params.require(:finance).permit(:audit, :cash_amount, :check_amount, :check_number, :data_entry, :note, :supporter_name)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def login
  	if user_signed_in?
		redirect_to finances_path
	end
  end
  
  def traineeFinance
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @schools = School.all
    respond_with(@schools)
  end

  def show
    respond_with(@school)
  end

  def new
    @school = School.new
    respond_with(@school)
  end

  def edit
  end

  def create
    @school = School.new(school_params)
    @school.save
    respond_with(@school)
  end

  def update
    @school.update(school_params)
    respond_with(@school)
  end

  def destroy
    @school.destroy
    respond_with(@school)
  end

  private
    def set_school
      @school = School.find(params[:id])
    end

    def school_params
      params.require(:school).permit(:name)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @teams = Team.all
    respond_with(@teams)
  end

  def show
    respond_with(@team)
  end

  def new
    @team = Team.new
    respond_with(@team)
  end

  def edit
  end

  def create
    @team = Team.new(team_params)
    @team.save
    respond_with(@team)
  end

  def update
    @team.update(team_params)
    respond_with(@team)
  end

  def destroy
    @team.destroy
    respond_with(@team)
  end

  private
    def set_team
      @team = Team.find(params[:id])
    end

    def team_params
      params.require(:team).permit(:name)
    end
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  before_action :set_year, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @years = Year.all
    respond_with(@years)
  end

  def show
    respond_with(@year)
  end

  def new
    @year = Year.new
    respond_with(@year)
  end

  def edit
  end

  def create
    @year = Year.new(year_params)
    @year.save
    respond_with(@year)
  end

  def update
    @year.update(year_params)
    respond_with(@year)
  end

  def destroy
    @year.destroy
    respond_with(@year)
  end

  private
    def set_year
      @year = Year.find(params[:id])
    end

    def year_params
      params.require(:year).permit(:year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/finances/_form.html.erb
<%= form_for(@finance) do |f| %>
  <% if @finance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
      <% @finance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :audit %><br>
    <%= f.text_field :audit %>
  </div>
  <div class="field">
    <%= f.label :cash_amount %><br>
    <%= f.text_field :cash_amount %>
  </div>
  <div class="field">
    <%= f.label :check_amount %><br>
    <%= f.text_field :check_amount %>
  </div>
  <div class="field">
    <%= f.label :check_number %><br>
    <%= f.text_field :check_number %>
  </div>
  <div class="field">
    <%= f.label :data_entry %><br>
    <%= f.number_field :data_entry %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :supporter_name %><br>
    <%= f.text_field :supporter_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/finances/edit.html.erb
<h1>Editing finance</h1>

<%= render 'form' %>

<%= link_to 'Show', @finance %> |
<%= link_to 'Back', finances_path %>

app/views/finances/index.html.erb
<h1>Listing finances</h1>

<table>
  <thead>
    <tr>
      <th>Audit</th>
      <th>Cash amount</th>
      <th>Check amount</th>
      <th>Check number</th>
      <th>Data entry</th>
      <th>Note</th>
      <th>Supporter name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @finances.each do |finance| %>
      <tr>
        <td><%= finance.audit %></td>
        <td><%= finance.cash_amount %></td>
        <td><%= finance.check_amount %></td>
        <td><%= finance.check_number %></td>
        <td><%= finance.data_entry %></td>
        <td><%= finance.note %></td>
        <td><%= finance.supporter_name %></td>
        <td><%= link_to 'Show', finance %></td>
        <td><%= link_to 'Edit', edit_finance_path(finance) %></td>
        <td><%= link_to 'Destroy', finance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Finance', new_finance_path %>

app/views/finances/new.html.erb
<h1>New finance</h1>

<%= render 'form' %>

<%= link_to 'Back', finances_path %>

app/views/finances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Audit:</strong>
  <%= @finance.audit %>
</p>

<p>
  <strong>Cash amount:</strong>
  <%= @finance.cash_amount %>
</p>

<p>
  <strong>Check amount:</strong>
  <%= @finance.check_amount %>
</p>

<p>
  <strong>Check number:</strong>
  <%= @finance.check_number %>
</p>

<p>
  <strong>Data entry:</strong>
  <%= @finance.data_entry %>
</p>

<p>
  <strong>Note:</strong>
  <%= @finance.note %>
</p>

<p>
  <strong>Supporter name:</strong>
  <%= @finance.supporter_name %>
</p>

<%= link_to 'Edit', edit_finance_path(@finance) %> |
<%= link_to 'Back', finances_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <a class="navbar-brand">KCM STSM 2015</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
		<% if user_signed_in? %>
			<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
		<% else %>
			<li><%= link_to "Sign in", new_user_session_path %></li>
		<% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KCM STSM 2015</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<% flash.each do |name,msg| %>
	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>

<%= render 'layouts/header' %>
<div class="container">
    <%= yield %>
</div>

</body>
</html>

app/views/pages/login.html.erb
<h1>KCM STSM 2015 Login</h1>
<p>
	<%= link_to "Create New User (Temporary)", new_user_registration_path %>
</p>
<p>
	<%= link_to "Sign in", new_user_session_path %>
</p>

app/views/pages/traineeFinance.html.erb
<h1> User's Finances </h1>
<p> Testing testing 1 2 3 </p>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>

app/views/years/_form.html.erb
<%= form_for(@year) do |f| %>
  <% if @year.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@year.errors.count, "error") %> prohibited this year from being saved:</h2>

      <ul>
      <% @year.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/years/edit.html.erb
<h1>Editing year</h1>

<%= render 'form' %>

<%= link_to 'Show', @year %> |
<%= link_to 'Back', years_path %>

app/views/years/index.html.erb
<h1>Listing years</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @years.each do |year| %>
      <tr>
        <td><%= year.year %></td>
        <td><%= link_to 'Show', year %></td>
        <td><%= link_to 'Edit', edit_year_path(year) %></td>
        <td><%= link_to 'Destroy', year, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Year', new_year_path %>

app/views/years/new.html.erb
<h1>New year</h1>

<%= render 'form' %>

<%= link_to 'Back', years_path %>

app/views/years/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @year.year %>
</p>

<%= link_to 'Edit', edit_year_path(@year) %> |
<%= link_to 'Back', years_path %>